apiVersion: v1
kind: Service
metadata:
  name: a2a-server
  namespace: ngx-agents
  labels:
    app: a2a-server
    component: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: a2a
  selector:
    app: a2a-server
    component: infrastructure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2a-server
  namespace: ngx-agents
  labels:
    app: a2a-server
    component: infrastructure
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a2a-server
      component: infrastructure
  template:
    metadata:
      labels:
        app: a2a-server
        component: infrastructure
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ngx-agents-sa
      containers:
      - name: a2a-server
        image: gcr.io/PROJECT_ID/ngx-agents-a2a:latest # TODO: Replace PROJECT_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: a2a
          protocol: TCP
        - containerPort: 8001
          name: metrics
          protocol: TCP
        env:
        - name: A2A_HOST
          value: "0.0.0.0"
        - name: A2A_PORT
          value: "9000"
        envFrom:
        - configMapRef:
            name: ngx-agents-config
        - configMapRef:
            name: ngx-agents-env
        - secretRef:
            name: ngx-agents-secrets
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: a2a
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: a2a
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - a2a-server
              topologyKey: kubernetes.io/hostname
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: a2a-server-pdb
  namespace: ngx-agents
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: a2a-server
      component: infrastructure