apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-agents-config
  namespace: ngx-agents
data:
  # A2A Server Configuration
  A2A_HOST: "a2a-server"
  A2A_PORT: "9000"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Vertex AI Configuration
  VERTEX_LOCATION: "us-central1"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  
  # Agent Ports
  ORCHESTRATOR_PORT: "9001"
  ELITE_TRAINING_PORT: "9002"
  NUTRITION_PORT: "9003"
  PROGRESS_TRACKER_PORT: "9004"
  BIOMETRICS_PORT: "9005"
  MOTIVATION_PORT: "9006"
  RECOVERY_PORT: "9007"
  SECURITY_PORT: "9008"
  INTEGRATION_PORT: "9009"
  BIOHACKING_PORT: "9010"
  CLIENT_SUCCESS_PORT: "9011"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-agents-env
  namespace: ngx-agents
data:
  # Environment-specific settings
  ENVIRONMENT: "production"
  APP_VERSION: "1.0.0"
  
  # Feature flags
  TELEMETRY_ENABLED: "true"
  USE_REDIS_CACHE: "true"
  
  # Performance settings
  MAX_WORKERS: "4"
  CONNECTION_POOL_SIZE: "10"
  REQUEST_TIMEOUT: "300"
  
  # Health check settings
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "10"