apiVersion: v1
kind: Namespace
metadata:
  name: ngx-agents
  labels:
    name: ngx-agents
    istio-injection: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ngx-agents-quota
  namespace: ngx-agents
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "10"
    services: "50"
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ngx-agents-limits
  namespace: ngx-agents
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "50Gi"
    type: PersistentVolumeClaim