apiVersion: v1
kind: Secret
metadata:
  name: ngx-agents-secrets
  namespace: ngx-agents
type: Opaque
stringData:
  # JWT Configuration
  JWT_SECRET: "your-jwt-secret-here" # TODO: Replace with actual secret
  JWT_ALGORITHM: "HS256"
  
  # Supabase Configuration
  SUPABASE_URL: "https://your-project.supabase.co" # TODO: Replace
  SUPABASE_ANON_KEY: "your-anon-key" # TODO: Replace
  
  # Database Configuration (for local Supabase)
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/ngx_agents"
  
  # Google Cloud Configuration
  VERTEX_PROJECT_ID: "your-gcp-project" # TODO: Replace
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: ngx-agents
type: Opaque
data:
  # Base64 encoded GCP service account key
  # Generate with: cat gcp-key.json | base64 -w 0
  gcp-key.json: "" # TODO: Add base64 encoded credentials